In [1]:
import pandas as pd
df=pd.read_csv("https://gist.githubusercontent.com/omairaasim/7845d01b0c2a777cc0cf2885ab499794/raw/9d87e438603954eb54bef60039dcd710ff27c2b4/project_1_dataset.csv")

In [2]:
df.to_csv(r'/home/rahul/Desktop/Jupyter Notebook\salary_dataset.csv')

In [3]:
df

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [4]:
x=df.iloc[:, :-1].values

In [5]:
x

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [6]:
x=df.iloc[:, :-1].values
y=df.iloc[:,-1].values

In [7]:
y

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [8]:
from sklearn.model_selection import train_test_split 
x_train ,x_test ,y_train, y_test = train_test_split(x, y , test_size=1/3)


In [9]:
x_train ,x_test ,y_train, y_test = train_test_split(x, y , test_size=1/3)

In [10]:
y_test

array([ 46205.,  55794.,  81363., 121872.,  54445., 113812.,  83088.,
        64445.,  98273.,  56642.])

In [11]:
y_test

array([ 46205.,  55794.,  81363., 121872.,  54445., 113812.,  83088.,
        64445.,  98273.,  56642.])

In [12]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)
y_pred=regressor.predict(x_test)

In [13]:
regressor = LinearRegression()

In [14]:
regressor.fit(x_train,y_train)

LinearRegression()

In [15]:
y_pred=regressor.predict(x_test)

In [16]:
x_test

array([[ 1.3],
       [ 4. ],
       [ 5.9],
       [10.5],
       [ 3.2],
       [ 8.2],
       [ 5.3],
       [ 3.2],
       [ 7.1],
       [ 2.9]])

In [17]:
y_test

array([ 46205.,  55794.,  81363., 121872.,  54445., 113812.,  83088.,
        64445.,  98273.,  56642.])

In [18]:
y_pred

array([ 35953.00773702,  61866.76424314,  80102.37067338, 124251.73360974,
        54188.61416725, 102177.05214156,  74343.75811646,  54188.61416725,
        91619.59578721,  51309.30788879])

In [19]:
import pandas as pd
df=pd.read_csv("https://gist.githubusercontent.com/omairaasim/7845d01b0c2a777cc0cf2885ab499794/raw/9d87e438603954eb54bef60039dcd710ff27c2b4/project_1_dataset.csv")
x=df.iloc[:, :-1].values
y=df.iloc[:,-1].values
from sklearn.model_selection import train_test_split 
x_train ,x_test ,y_train, y_test = train_test_split(x, y , test_size=1/3)
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)
y_pred=regressor.predict(x_test)

In [20]:
df

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [21]:
x_test

array([[1.1],
       [1.3],
       [8.2],
       [2.9],
       [7.9],
       [2. ],
       [3.2],
       [6.8],
       [4.1],
       [3. ]])

In [22]:
y_pred

array([ 32551.23741457,  34521.9747762 , 102512.41375235,  50287.87366922,
        99556.30770991,  41419.55554189,  53243.97971166,  88717.25222096,
        62112.29783898,  51273.24235003])

In [23]:
regressor().score(x_train,y_train)

TypeError: 'LinearRegression' object is not callable

In [ ]:
regressor.score(x_test,y_pred)

In [ ]:
plt.scatter(x_train, y_train, color="red")

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.scatter(x_train,y_train, color='red')

In [ ]:
import pandas as pd
df=pd.read_csv("https://gist.githubusercontent.com/omairaasim/7845d01b0c2a777cc0cf2885ab499794/raw/9d87e438603954eb54bef60039dcd710ff27c2b4/project_1_dataset.csv")
x=df.iloc[:, :-1].values
y=df.iloc[:,-1].values
from sklearn.model_selection import train_test_split 
x_train ,x_test ,y_train, y_test = train_test_split(x, y , test_size=1/3)
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)
y_pred=regressor.predict(x_test)

In [ ]:
plt.scatter(x_train,y_train, color='red')
plt.plot(x_train, regressor.predict(x_train), color='blue')

plt.scatter(x_test,y_test)

In [ ]:
plt.scatter(x_test,y_test)
plt.plot(x_test, regressor.predict(x_test))

In [ ]:
plt.plot(x_test, regressor.predict(x_test))

In [ ]:
regressor.predict([[15]])

In [ ]:
regressor.score(x_test, y_pred)

In [ ]:
x

In [ ]:
x


In [ ]:
y

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:

plt.show()

In [ ]:
plt.scatter(x,y)

In [ ]:
h =np.random.normal(4,1,50)

In [ ]:
plt.hist(h,100)

In [ ]:
plt.show()

In [ ]:
import pandas as pd
df=pd.read_csv("https://gist.githubusercontent.com/omairaasim/7845d01b0c2a777cc0cf2885ab499794/raw/9d87e438603954eb54bef60039dcd710ff27c2b4/project_1_dataset.csv")

In [ ]:
df.plot(kind="line")

In [ ]:
import pandas as pd
df=pd.read_csv("https://gist.githubusercontent.com/omairaasim/7845d01b0c2a777cc0cf2885ab499794/raw/9d87e438603954eb54bef60039dcd710ff27c2b4/project_1_dataset.csv")

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
df

In [ ]:
x=df.iloc[:,-2]

In [ ]:
x

In [ ]:
y=df.iloc[: ,-1]

In [ ]:
plt.scatter(x,y)
plt.show()

In [ ]:
import numpy as np

In [ ]:
plt.scatter(x,y)
plt.plot(np.unique(x), np.poly1d(np.polyfit(x, y, 1))(np.unique(x)))
plt.show()


In [24]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/home/rahul/.local/lib/python3.6/site-packages/tensorflow/_api/v2/version/__init__.py'>
